# Find all the available rules by running:
# swiftlint rules
disabled_rules:
 - force_cast 
 - force_try 
 - trailing_whitespace

analyzer_rules:
 - explicit_self
 - unused_import
 - unused_private_declaration

opt_in_rules:
 - unneeded_parentheses_in_closure_argument
 - operator_usage_whitespace
 - anyobject_protocol
 - prohibited_super_call
 - closure_spacing
 - contains_over_first_not_nil
 - convenience_type
 - empty_string
 - fallthrough
 - first_where
 - literal_expression_end_indentation
 - overridden_super_call
 - override_in_extension
 - sorted_imports
 - vertical_whitespace_closing_braces
 - vertical_whitespace_opening_braces

included:
 - Sources
large_tuple: 5 
line_length: 150
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - up
    - i
    - to
reporter: "xcode"
